cockroachdb_data_dir: "/var/{{ cockroachdb_product }}"
cockroachdb_log_dir: "/var/log/{{ cockroachdb_product }}"
cockroachdb_pid_dir: "/run/{{ cockroachdb_product }}"
cockroachdb_pid_file: "{{ cockroachdb_pid_dir }}/{{ cockroachdb_product }}.pid"

cockroachdb_ports:
  http: "{{ cockroachdb_ports_http | default('8080', true) }}"
  server: "{{ cockroachdb_ports_server | default('26257', true) }}"

cockroachdb_security_mode: "secure"
